const Parte2 = () => {
    return (
        <>
            <rect
                  className="cls-5 assign-color"
                  x="157.31"
                  y="200.13"
                  width="217.37"
                  height="1.95"
                />
                <rect
                  className="cls-8"
                  x="246.51"
                  y="163.37"
                  width="153.98"
                  height="1.95"
                />
                <rect
                  className="cls-8"
                  x="400.92"
                  y="181.75"
                  width="32.18"
                  height="1.95"
                />
                <rect
                  className="cls-8"
                  x="135.64"
                  y="172.56"
                  width="9.94"
                  height="1.95"
                />
                <rect
                  className="cls-9"
                  x="135.64"
                  y="181.75"
                  width="9.94"
                  height="1.95"
                />
                <rect
                  className="cls-8"
                  x="157.31"
                  y="181.75"
                  width="58.74"
                  height="1.95"
                />
                <rect
                  className="cls-8"
                  x="232.81"
                  y="190.94"
                  width="169.78"
                  height="1.94"
                />
                <rect
                  className="cls-5 assign-color"
                  x="222.01"
                  y="181.75"
                  width="169.71"
                  height="1.95"
                />
                <rect
                  className="cls-8"
                  x="135.64"
                  y="190.94"
                  width="9.94"
                  height="1.94"
                />
                <rect
                  className="cls-8"
                  x="135.64"
                  y="209.33"
                  width="9.94"
                  height="1.95"
                />
                <rect
                  className="cls-8"
                  x="157.31"
                  y="209.33"
                  width="116.53"
                  height="1.95"
                />
                <rect
                  className="cls-8"
                  x="135.64"
                  y="218.52"
                  width="9.94"
                  height="1.95"
                />
                <rect
                  className="cls-9"
                  x="166.99"
                  y="218.52"
                  width="74.82"
                  height="1.95"
                />
                <rect
                  className="cls-9"
                  x="157.31"
                  y="246.09"
                  width="71.46"
                  height="1.95"
                />
                <rect
                  className="cls-9"
                  x="222.69"
                  y="227.71"
                  width="186.36"
                  height="1.95"
                />
                <rect
                  className="cls-8"
                  x="400.92"
                  y="236.9"
                  width="32.18"
                  height="1.95"
                />
                <rect
                  className="cls-8"
                  x="135.64"
                  y="227.71"
                  width="9.94"
                  height="1.95"
                />
                <rect
                  className="cls-9"
                  x="135.64"
                  y="236.9"
                  width="9.94"
                  height="1.95"
                />
                <rect
                  className="cls-8"
                  x="157.31"
                  y="236.9"
                  width="58.74"
                  height="1.95"
                />
                <rect
                  className="cls-8"
                  x="232.81"
                  y="246.09"
                  width="169.78"
                  height="1.95"
                />
                <rect
                  className="cls-5 assign-color"
                  x="222.01"
                  y="236.9"
                  width="169.71"
                  height="1.95"
                />
                <rect
                  className="cls-8"
                  x="135.64"
                  y="246.09"
                  width="9.94"
                  height="1.95"
                />
        </>
    )
}

export default Parte2